### ISSUE TITLE
Outdated `env.example` file?

### ISSUE THREAD

**Issue by MerlinEgalite** [alcueca/erc7399-wrappers#34]
It seem that the `env.example` file is a bit outdated since when running `forge test` I encountered the following:

<img width="1060" alt="image" src="https://github.com/alcueca/erc7399-wrappers/assets/44097430/282ac81a-3cd7-47ad-bca7-2eaf589761a8">

Resolved only by setting this specific environment variable in my `.env` file. Am I missing something?

**Comment by ultrasecreth** [comment]
Yeah, I just went ahead and deleted it, the ENV vars that are needed are the ones used by `foundry.toml`
