### ISSUE TITLE
callBackResult = ""

### ISSUE THREAD

**Issue by devtooligan** [alcueca/erc7399-wrappers#6]
https://github.com/alcueca/erc7399-wrappers/blob/acfe8b4216747ed6965190bd96c2992e82395f50/src/erc3156/ERC3156Wrapper.sol#L91-L92

> Confirm that this deletes the storage variable

It does.  You could also do `delete  _callbackResult` which is more readable and should save 150 runtime gas.  Additionally, if you wanted to save more gas you could have a non-zero value represent empty similar to how 1 and 2 are used in the re-entrancy guard instead of 1 and 0.

**Comment by ultrasecreth** [comment]
Yeah. the aave implementation already handles that, currently generalising it into a base contract.
I like the idea of not having a zero value, it could have a hash of some string like they do for most EIPs

**Comment by alcueca** [comment]
Fixed already
